# -*- coding: utf-8 -*-
"""API_GITHUB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_H0uGBaoK-s9if_DgoezHqgMyLZG6J6f
"""

pip install requests

import requests
username = input('Qual é o seu usuario?')
print(username)
url = f'https://api.github.com/users/{username}'

response = requests.get(url)
data = response.json()

if response.status_code == 200:
  print(data)
  print(f'Nome completo do Usuario {data["name"]}')
  print(f'Biografia {data["bio"]}')
  print(f'User Name {data["login"]}')
  print(f'Seguidores {data["followers"]}')
  print(f'Seguindo {data["following"]}')
  print(f'Repos {data["public_repos"]}')
else:
    print('Usuario não encontrado')

df = pd.DataFrame([data])
df = df.drop(['avatar_url','html_url','followers_url','following_url','gists_url','email','repos_url','organizations_url','twitter_username'], axis=1)

df

